# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute LD matrix using GCTA-style formula matching the DENTIST binary.
#'
#' This function computes pairwise Pearson correlations from a genotype matrix
#' using the exact same formula and floating-point operation order as the
#' original DENTIST C++ binary (calcLDFromBfile_gcta in bfileOperations.cpp).
#' Key differences from R's crossprod-based approach:
#'   1. Accumulates integer-valued sums sequentially (exact intermediate values)
#'   2. Handles per-pair missing data with GCTA correction formula
#'   3. Divides by nKeptSample (trimmed to multiple of 4), not nrow(X)
#'
#' @param X Numeric genotype matrix (samples x SNPs), values in {0, 1, 2, NA}.
#'          Rows should already be trimmed to a multiple of 4.
#' @param ncpus Number of CPU threads for parallel computation.
#' @return Symmetric LD correlation matrix with 1.0 on diagonal.
compute_LD_gcta_cpp <- function(X, ncpus = 1L) {
    .Call('_pecotmr_compute_LD_gcta_cpp', PACKAGE = 'pecotmr', X, ncpus)
}

dentist_iterative_impute <- function(LD_mat, nSample, zScore, pValueThreshold, propSVD, gcControl, nIter, gPvalueThreshold, ncpus, correct_chen_et_al_bug, verbose = FALSE) {
    .Call('_pecotmr_dentist_iterative_impute', PACKAGE = 'pecotmr', LD_mat, nSample, zScore, pValueThreshold, propSVD, gcControl, nIter, gPvalueThreshold, ncpus, correct_chen_et_al_bug, verbose)
}

prs_cs_rcpp <- function(a, b, phi, bhat, maf, n, ld_blk, n_iter, n_burnin, thin, verbose, seed) {
    .Call('_pecotmr_prs_cs_rcpp', PACKAGE = 'pecotmr', a, b, phi, bhat, maf, n, ld_blk, n_iter, n_burnin, thin, verbose, seed)
}

qtl_enrichment_rcpp <- function(r_gwas_pip, r_qtl_susie_fit, pi_gwas = 0, pi_qtl = 0, ImpN = 25L, shrinkage_lambda = 1.0, num_threads = 1L) {
    .Call('_pecotmr_qtl_enrichment_rcpp', PACKAGE = 'pecotmr', r_gwas_pip, r_qtl_susie_fit, pi_gwas, pi_qtl, ImpN, shrinkage_lambda, num_threads)
}

sdpr_rcpp <- function(bhat, LD, n, per_variant_sample_size = NULL, array = NULL, a = 0.1, c = 1.0, M = 1000L, a0k = 0.5, b0k = 0.5, iter = 1000L, burn = 200L, thin = 5L, n_threads = 1L, opt_llk = 1L, verbose = TRUE) {
    .Call('_pecotmr_sdpr_rcpp', PACKAGE = 'pecotmr', bhat, LD, n, per_variant_sample_size, array, a, c, M, a0k, b0k, iter, burn, thin, n_threads, opt_llk, verbose)
}

